duckie-team/quack-quack-android

gradle-conventions/settings.gradle.kts
gradle-conventions/src/main/kotlin/ApplicationComposePlugin.kt
gradle-conventions/src/main/kotlin/ApplicationJacocoPlugin.kt
gradle-conventions/src/main/kotlin/ApplicationPlugin.kt
gradle-conventions/src/main/kotlin/LibraryComposePlugin.kt
gradle-conventions/src/main/kotlin/LibraryComposeUiTestPlugin.kt
gradle-conventions/src/main/kotlin/LibraryJacocoPlugin.kt
gradle-conventions/src/main/kotlin/LibraryPlugin.kt
gradle-conventions/src/main/kotlin/LintPlugin.kt

refactor: 그레이들 코드 포맷팅

---

.github/workflows/android-ci.yml

feat: CI 에 테스트 및 빌드 추가

---

.github/workflows/android-cd.yml

feat: cd 에서 labeled 타입 제거

---

.github/workflows/android-cd.yml

feat: cd label 체크 로직 변경

---

lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/empty.kt
lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/empty.kt
lint-quack/build.gradle.kts
lint-quack/src/main/AndroidManifest.xml
lint-quack/src/main/kotlin/team/duckie/quack/lint/quack/DesignSystemDetector.kt
lint-quack/src/main/kotlin/team/duckie/quack/lint/quack/DesignSystemIssueRegistry.kt
lint-quack/src/main/resources/META-INF/services/com.android.tools.lint.client.api.IssueRegistry
lint-quack/src/test/kotlin/team/duckie/quack/lint/quack/DesignSystemTest.kt
playground/build.gradle.kts
playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
settings.gradle.kts

- `lint-compose` 에 있던 DesignSystem 규칙을 `lint-quack` 개별 모듈로 분리하였습니다.

lint-quack 분리

---

.github/workflows/android-ci.yml

refactor: ci 중복 과정 제거

---

lint-quack/src/main/kotlin/team/duckie/quackquack/lint/quack/DesignSystemDetector.kt
lint-quack/src/main/kotlin/team/duckie/quackquack/lint/quack/DesignSystemIssueRegistry.kt
lint-quack/src/main/resources/META-INF/services/com.android.tools.lint.client.api.IssueRegistry
lint-quack/src/test/kotlin/team/duckie/quackquack/lint/quack/DesignSystemTest.kt

- team.duckie.quack 에서 team.duckie.quackquack 으로 패키지명 통일

refactor: quack 에서 quackquack 으로 패키지명 통일

---

.github/workflows/android-cd.yml
.github/workflows/android-ci.yml
.github/workflows/dokka-deploy.yml

1. 기존 CI/CD 에서 필요 없는 옵션 제거
2. dokka 컨텐츠 배포를 위한 CD 구성

dokka 컨텐츠 배포를 위한 CD 구성

---

.github/workflows/android-ci.yml
.idea/dictionaries/jisungbin.xml

1. CI 에 테스트 커버리지 Codecov 로 보내는 단계 추가

Codecov 설정

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/android-ci.yml
build.gradle.kts

1. PR template 에 label 내용 추가
2. CI 에 test coverage html report 구성 파일 추가하는 과정 추가

템플릿 및 CI 조정

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/android-cd.yml

1. android-cd 활성화를 위한 `release` label 추가
2. 기존 android-cd 활성화 label 에서 `UI` 에서 `release` 로 변경

feat: release label 추가

---

build.gradle.kts

1. https://github.com/sungbinland/duckie-quack-quack/issues/65 해결

chore: configurationUiComponentsSnapshotDeploy 로직 개선

---

documents/test/snapshot-test.md

1. snapshot test 에 font scale 테스트 필수로 추가

docs: font scale 테스트 규칙 추가

---

ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/Extension.kt
ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/TagTest.kt
ui-components/src/androidTest/kotlin/team/duckie/quackquack/ui/TypographyTest.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/color.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/icon.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/text.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/constant/padding.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/constant/shape.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/style.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/typography/typography.kt
ui-components/src/main/res/drawable/ic_close_24.xml

1. QuackTypography
2. QuackTag
3. QuackTab
이 추가 되었습니다. 아직 DDD나 OOP관점에서 코드 스트럭쳐는 좀 더 다듬어야할듯한데 일단 develop에 넣어놓고 새로운 피쳐 개발하면서 리팩토링 같이 가져갈게요.
커밋이 많아서 diff로 확인하기보다는 componenet 패키지에 있는 파일 위주로 한 번 봐주시고 전체적으로 리뷰 남겨주시면 감사하겠습니다.

타이포그래피, 태그,탭 추가

---

common-lint/src/main/kotlin/team/duckie/quackquack/common/lint/KDocChecker.kt
detekt-config.yml
lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/CoreIssueRegistry.kt
lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/KDocFieldsDetector.kt
lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/KDocFieldsTest.kt

1. 지난 KDoc 에서 나온 개선사항 내용을 반영했습니다. (#82)
2. 지난 번 revert 된 내용도 다시 합쳐질 예정입니다. (#89)

KDocFields 린트 규칙 구현 (2차)

---

.github/workflows/android-cd.yml
.github/workflows/android-ci.yml
.github/workflows/dokka-deploy.yml

- Fix the problem that CI failing in external PR (see: https://github.com/sungbinland/duckie-quack-quack/pull/102#issuecomment-1244937186)

Fix the problem that CI failing in external PR

---

.idea/dictionaries/jisungbin.xml
detekt-config.yml
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt

1. Uncomment the code in QuackTextField
2. Changed the comment used in the QuackTextField code to English
- This PR opens up two contributable issues.

refactor: QuackTextField code cleanup

---

README.md
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt

updated textfield.kt comments

---

playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TextFieldPlayground.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt
ui-components/src/test/kotlin/team/duckie/quackquack/ui/QuackTextField.kt

1. 스냅샷 테스트 작성
2. textFieldPlaceable height 초기화 방식 `Infinity` 로 변경
3. Playground 에서 QuackTextField 만 단독으로 보여주게 임시 업데이트 (주요 디버깅)

QuackTextField 일부 개선

---

common-lint/src/main/kotlin/team/duckie/quackquack/common/lint/util/KotlinUtils.kt
detekt-config.yml
lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/CoreIssueRegistry.kt
lint-core/src/main/kotlin/team/duckie/quackquack/lint/core/SpecifyLambdaParamsNameDetector.kt
lint-core/src/test/kotlin/team/duckie/quackquack/lint/core/SpecifyLambdaParamsNameTest.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/FabPlayground.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt

1. SpecifyLambdaParamsNameIssue 를 추가하였습니다.
2. 관련 테스트 코드를 추가하였습니다.
3. 람다 내에 파라미터가 없는 케이스가 있을지 모르겠어서 일단 TODO 로 두었습니다.
해당 내용 의견 주시면 반영하겠습니다. (없다고 이야기되면 TODO 삭제 커밋 추가 예정입니다.)

SpecifyLambdaParamsName 구현

---

build-logic/src/main/kotlin/AndroidQuackPublishPlugin.kt
build-logic/src/main/kotlin/team/duckie/quackquack/convention/QuackPublishExtension.kt
gradle/libs.versions.toml
lint-compose-publish/build.gradle.kts
lint-core-publish/build.gradle.kts
lint-quack-publish/build.gradle.kts
quack-publish-bom/build.gradle.kts
ui-components/build.gradle.kts

quack publish code cleanup

---

lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/TrailingCommaDetector.kt
lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/TrailingCommaTest.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/base/common.kt

* 후행 콤마를 인식하지 못하는 버그를 수정
* 테스트케이스 추가
* Detector에서 후행 콤마를 감지하는 로직 수정

TrailingComma 버그 수정

---

ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt

- TextField 에 `handleColor`, `backgroundColor` 색상 지정 ([참고](https://sungbinland.slack.com/archives/C03CM18M529/p1664463107017239?thread_ts=1664459566.901359&cid=C03CM18M529))

feat: 땡땡이랑 형광팬 색상 지정

---

.github/workflows/android-ci.yml

- CI 에서 테스트 커버리지 부분 정리
- https://github.com/duckie-team/duckie-quack-quack/issues/129 에서 Codecov 부분 문제 해결 시도

feat: CI 에서 테스트 커버리지 step 정리

---

.github/workflows/android-ci.yml

- Set codecov token to `codecov-action`

feat: set codecov token

---

.github/workflows/android-ci.yml
.github/workflows/artifact-publish.yml

- [CI jobs 이름 변경](https://github.com/duckie-team/duckie-quack-quack/commit/47c42ff821d665f5e4593938430c3312437f413c)

chore: CI jobs 이름 변경

---

.github/workflows/artifact-build.yml
.github/workflows/artifact-publish.yml
.github/workflows/playground-release.yml

- #129 
- CI/CD 빌드 에러 수정
- 배포 성공시 슬랙에 메시지 전송하는 step 추가

CI/CD 빌드 에러 수정

---

playground-version.txt

chore: bump playground version

---

.github/workflows/android-ci.yml
.github/workflows/artifact-build.yml
.github/workflows/artifact-publish.yml
.github/workflows/playground-release.yml
playground-version.txt

publish new version

---

.github/workflows/artifact-publish.yml

- close https://github.com/duckie-team/duckie-quack-quack/issues/188
- env 광역으로 이동 및 키 재지정 (조직 secrets)

refactor: publish env 설정 간소화

---

.github/workflows/artifact-publish.yml
.github/workflows/playground-release.yml

- CI 로 인해 생기는 version bump 는 @sungbinland-bot 계정으로 커밋하도록 설정

feat: committer bot 설정

---

gradle/libs.versions.toml

- Bump Koltin and Compose Complier

chore: bump Koltin and Compose Complier

---

playground/build.gradle.kts
settings.gradle.kts
ui-components/build.gradle.kts
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/internal/QuackText.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/modifier/draw.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/modifier/lifecycle.kt
ux-writing-model/build.gradle.kts
ux-writing-model/src/main/AndroidManifest.xml
ux-writing-model/src/main/kotlin/team/duckie/quackquack/uxwriting/model/model.kt
ux-writing-overlay/build.gradle.kts
ux-writing-overlay/src/androidTest/kotlin/team/duckie/quackquack/uxwriting/overlay/UxWritingOverlayInstrumentationTest.kt
ux-writing-overlay/src/main/AndroidManifest.xml
ux-writing-overlay/src/main/kotlin/team/duckie/quackquack/uxwriting/overlay/fastForEach.kt
ux-writing-overlay/src/main/kotlin/team/duckie/quackquack/uxwriting/overlay/overlay.kt
ux-writing-rule/build.gradle.kts
ux-writing-rule/src/main/AndroidManifest.xml
ux-writing-rule/src/main/kotlin/team/duckie/quackquack/uxwriting/rule/rules.kt
ux-writing-rule/src/test/kotlin/team/duckie/quackquack/uxwriting/rule/UxWritingRuleTest.kt

feat: ux-writing-overlay 구현 시도

---

gradle/libs.versions.toml
ui-components/src/main/kotlin/team/duckie/quackquack/ui/border/QuackBorder.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tab.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/textstyle/QuackTextStyle.kt

- close #207 
- [chore: bump AGP to 8.0.0-alpha03](https://github.com/duckie-team/duckie-quack-quack/commit/8a881a315b5459b224fcf772b7e7c53ce9ae335f)
- [refactor: animationSpec 으로 quackAnimationSpec() 사용하도록 설정](https://github.com/duckie-team/duckie-quack-quack/commit/f92b15b46d2b770dc08d2f787a47641022429854)

feat: animateAsState 빌드 에러 해결

---

gradle/libs.versions.toml

Reverts duckie-team/duckie-quack-quack#220
---
dev 버전은 조금 위험해 보임

Revert "fix(deps): update dependency androidx.datastore:datastore-preferences to v1.1.0-dev01"

---

playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/base/common.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/util/datastore.kt
ui-components-benchmark-app/src/main/kotlin/team/duckie/quackquack/ui/benchmark/app/benchmark.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/textstyle/QuackTextStyle.kt

- close #230 
- QuackFontScale 에서 Density 로 변경

refactor: QuackFontScale 제거

---

playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TogglePlayground.kt
ui-components/api/ui-components.api
ui-components/src/main/kotlin/team/duckie/quackquack/ui/color/QuackColor.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/image.kt

- close #232 
- QuackIcon 은 Modfier.paint 로 그리게 변경

feat: QuackIcon 표시 방법 변경

---

.github/workflows/android-ci.yml
.github/workflows/artifact-build.yml
.github/workflows/artifact-publish.yml
.github/workflows/playground-release.yml
.github/workflows/update-snapshots.yml
.github/workflows/verify-snapshots-failed-comment.yml
.github/workflows/verify-snapshots.yml
.gitignore
build-logic/build.gradle.kts
build.gradle.kts
buildSrc/build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackButton.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackFab.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackTab.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackTag.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackTextField.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackToggle.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/provider/QuackDeviceConfig.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/util/paparazzi.kt

- close #199 #219 #200 
- gradle scan 라이선스 동의 로직 추가
- paparazzi 복구
- 스냅샷 검증 CI 추가

feat: snapshots 관련 CI 및 로직 추가

---

ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackButton.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackTab.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackTag.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackTextField.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/QuackToggle.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/rule/AnimationTestRule.kt
ui-components-snapshots/src/test/kotlin/team/duckie/quackquack/ui/snapshot/util/paparazzi.kt

- close #240 
- paparazzi 디바이스 사이즈 조절 유틸 추가

feat: snapshot utils

---

ui-components-benchmark-app/src/main/kotlin/team/duckie/quackquack/ui/benchmark/app/benchmark.kt
ui-components/api/ui-components.api
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/typography.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/textstyle/QuackTextStyle.kt

최근 디자인시스템에 추가된 QuackSubtitle2를 추가하였습니다.

feat: QuackSubTitle2 추가

---

README.md

- Download 에 warning 추가
- Contribute 개선
- Maintainers, Tech Stacks 세션 추가

docs: 리드미 개선

---

playground/src/main/AndroidManifest.xml
playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TextAreaPlayground.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/border/QuackBorder.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/selectableImage.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textarea.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/modifier/border.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/util/textfield.kt

- Modifier.quackBorderOrNull 재구현 
- QuackBorderTextArea 구현
- QuackTextArea 구현
- TextField 색상 조정을 위한 extension 추가

QuackTextArea 구현

---

README.md
gradle/libs.versions.toml
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TagPlayground.kt
quackquack-version/ui-components.txt
ui-components/build.gradle.kts
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/theme/QuackTheme.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/util/effect.kt

- 리드미 개선
- QuackTagType 문서화 보충
- QuackSingleRowTag 추가 구현
- QuackRowTag 재구현
- 리드미 개선이랑 QuackTag 재구현이랑 분리하고 싶었는데.. 제가 브런치를 잘못 만들어서 합쳐졌네요 ㅠㅅㅠ 재송함니다

문서화 보충 및 QuackTag 일부 재구현

---

playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/EtcPlayground.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TextFieldPlayground.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/card.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/gridLayout.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/image.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/internal/QuackText.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textfield.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/typography.kt

- QuackHeader & QuackFooter GridLayout에서 0개일때도 해당 아이템 그리기
- QuackMultiline crossAxisSpacing 추가
- QuackMultLineRow에 onClick 추가
- QuackCardImage에 onClick 추가
- QuackTextField에 focus 관리 기능 추가
- Typography에 overflow 기능 추가

컴포넌트 디자인 및 기능 디테일 수정

---

playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TogglePlayground.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/textarea.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/toggle.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/icon/QuackIcon.kt
ui-components/src/main/res/drawable/quack_ic_gallery_24.xml

- Toggle 컴포넌트 오른쪽에 Title 붙일 수 있도록 수정
- QuackTextArea 상단 패딩값 수정
- SquareCheckBoxSize 값 수정
- Gallery Icon 수정

컴포넌트 디자인 디테일 수정

---

.github/workflows/artifact-snapshot-publish.yml
.github/workflows/artifact-stable-publish.yml
assets/coverage.svg

- change `main` branch to `master` branch

feat: change main branch to master branch

---

.github/workflows/artifact-snapshot-publish.yml
.github/workflows/artifact-stable-publish.yml
.github/workflows/playground-release.yml

- fix quack-label-filter-actions version

fix quack-label-filter-actions version

---

README.md

- Fix broken snapshot repository links

Fix snapshot repository links

---

.github/workflows/artifact-snapshot-publish.yml

- Close https://github.com/duckie-team/duckie-quack-quack-mvp/issues/317

Fix has_target if issue

---

README.md

* README에 LINT 관련 내용을 update 하였습니다.

docs: improve lint readme

---

assets/coverage.svg
build.gradle.kts

chore: ui-components 와 lint 모듈만 테스트 커버리지 산출하게 설정

---

renovate.json

- close #336 
- 모든 업데이트를 그룹화하고 매일 업데이트하도록 Renovate 설정 변경

Renovate 설정 업데이트

---

.github/workflows/auto-approve.yml

feat: add auto-approve action

---

gradle/libs.versions.toml
ui-components/src/main/kotlin/team/duckie/quackquack/ui/animation/QuackAnimatedContentTransform.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/image.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/internal/QuackText.kt

feat: AnimatedContentTransform public 으로 수정

---

.github/workflows/android-ci.yml

- close https://github.com/duckie-team/quack-quack-android/issues/353

feat: committer 지정

---

ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/internal/dimmed.kt

refactor: dimmed 리팩토링

---

ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/internal/TextFieldImpl.kt

- `TextFieldImpl` 에 누락된 일부 문서화 보충

refactor: TextFieldImpl 문서화 보충

---

build-logic/build.gradle.kts
build-logic/src/main/kotlin/AndroidApplicationPlugin.kt
build-logic/src/main/kotlin/AndroidCommonLintPlugin.kt
build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
build-logic/src/main/kotlin/AndroidLintPlugin.kt
build-logic/src/main/kotlin/AndroidQuackUiComponentsBenchmarkPlugin.kt
build-logic/src/main/kotlin/JvmLibraryPlugin.kt
build-logic/src/main/kotlin/team/duckie/quackquack/convention/PluginEnum.kt
build-logic/src/main/kotlin/team/duckie/quackquack/convention/QuackPublishExtension.kt
gradle.properties
gradle/libs.versions.toml

refactor: cleanup codebase

---

.github/workflows/android-ci.yml
.github/workflows/artifact-snapshot-publish.yml
.github/workflows/artifact-stable-publish.yml
.github/workflows/playground-release.yml
ui-components/api/ui-components.api
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt

- CI/CD 를 활성화합니다.
- QuackLargeButton 의 ImeAnimation 사용 여부를 인자에 추가하였습니다.

feat: CI/CD 활성화 및 imeAnimation 인자로 분리

---

playground/src/main/AndroidManifest.xml
playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/IndicatorPlayground.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TagPlayground.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TextFieldPlayground.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TogglePlayground.kt
ui-components/api/ui-components.api
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/TextArea.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/TextField.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/TopAppBar.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/indicator.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/internal/TextFieldImpl.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/toggle.kt
versions/ui-components.txt

- https://github.com/duckie-team/quack-quack-android/issues/411
- https://github.com/duckie-team/quack-quack-android/issues/413
- https://github.com/duckie-team/quack-quack-android/issues/412
- https://github.com/duckie-team/quack-quack-android/issues/407

publish 1.4.1

---

playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/ButtonPlayground.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TogglePlayground.kt
ui-components/build.gradle.kts
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/TextField.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/toggle.kt
versions/ui-components.txt

publish 1.4.2

---

playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/ButtonPlayground.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/dialog.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/fab.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/image.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/internal/surface.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/label.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/surface.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/tag.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/toggle.kt
versions/ui-components.txt

- `QuackWeight1MediumButton` 을 제거하였습니다.
- `QuackSurface` 를 publish 으로 변경하였습니다.

publish 1.4.3

---

playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/ButtonPlayground.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/DropDownPlayground.kt
playground/src/main/kotlin/team/duckie/quackquack/playground/realworld/TextFieldPlayground.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/DropDown.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/TextField.kt
ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt
versions/ui-components.txt

publish 1.4.4

---

core/build.gradle.kts
core/src/main/AndroidManifest.xml
settings.gradle.kts

- 2.x.x 버전 개발을 위해 `core` 모듈을 추가하고 등록합니다.

chore: 2.x.x 개발을 위한 core 모듈 추가

---

.editorconfig
.run/style_checks.run.xml
core-aide-annotation/src/main/kotlin/team/duckie/quackquack/aide/annotation/annotations.kt
core-aide-processor/build.gradle.kts
core-sugar-processor/build.gradle.kts
core/src/main/kotlin/team/duckie/quackquack/core/material/icon.kt
gradle.properties
gradle/libs.versions.toml
playground/src/main/kotlin/team/duckie/quackquack/playground/MainActivity.kt
settings.gradle.kts

- bump ktlint and update ktlint rules
- add ksp-api dependency
- update gradle properties
- create style_checks build configuration
- code styling with new ktlint rules

chore: improve project backend

---

.run/build.run.xml
buildSrc/src/main/kotlin/DependencyHandlerExtensions.kt
core-aide-annotation/src/main/kotlin/team/duckie/quackquack/aide/annotation/annotations.kt
core-aide-processor/build.gradle.kts
core-aide/build.gradle.kts
core-sugar-processor/build.gradle.kts
core/build.gradle.kts
core/src/main/kotlin/team/duckie/quackquack/core/component/text.kt
gradle/libs.versions.toml
settings.gradle.kts

- add google/autoservice dependencies
- downgrade ksp dependency

chore: configure ksp and autoservice

---

core-sugar-processor-kotlinc/src/main/kotlin/ir/SugarIrData.kt
core-sugar-processor-kotlinc/src/main/kotlin/names.kt
core-sugar-processor-kotlinc/src/main/kotlin/poet/poet.kt

- `ClassName#bestGuess` 작업을 싱글톤으로 진행합니다.

code cleanup

---

.github/workflows/dependabot-automerge.yml

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

Create dependabot automerge actions

---

.github/workflows/website-deploy.yml

- Create `website-deploy` job for deploying website

Create website-deploy job

---

.github/workflows/website-deploy.yml

Fix deploy job errors

---

README.md
website/docs/01-intro.mdx

The design system is a really big concept, and what we're building now is more of a UI kit.

Correct design system to ui kit

---

.github/workflows/android-ci.yml

- Specify `cache-write-only` and `cache-read-only` options in gradle-build-action.

Trying to troubleshoot gradle-build-action caching

---

ui/src/main/kotlin/team/duckie/quackquack/ui/text.kt

Resolve quote todo

---

ui/src/main/kotlin/team/duckie/quackquack/ui/button.kt

- 변경된 타이포그래피 반영
- 불필요한 inspection 제거
- 인자 순서 개선

Improve QuackButton

---

.github/workflows/android-ci.yml

bug: Local environment-based logic annotation processing
